/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package deu.cse.moviereservationsystem.view.SweetShop;

import deu.cse.moviereservationsystem.Pattern.SweetShopObserver.Displayment;
import deu.cse.moviereservationsystem.Pattern.SweetShopObserver.Observer;
import deu.cse.moviereservationsystem.Pattern.SweetShopObserver.OrderList;
import deu.cse.moviereservationsystem.view.InputImage;
import deu.cse.moviereservationsystem.Pattern.SweetShopFacade;
import deu.cse.moviereservationsystem.view.User.UserMainFrame;

/**
 *
 * @author LG
 */
public class SweetShopFrame extends javax.swing.JFrame implements Observer,Displayment{

    /**
     * Creates new form SweetShopFrame
     */
    private static SweetShopFrame instance; 
    
    InputImage input = new InputImage();
    int countOrder;
    private OrderList order;
    private String menu;
    private String size;
    private int cost;
    
    private SweetShopFrame() {
        initComponents();
        setLocationRelativeTo(null);
        inputImage();
    }
    
   public static SweetShopFrame getInstance() { //싱글턴 패턴 사용
        if (instance == null) { // 인스턴스가 없는 경우에만 생성
            instance = new SweetShopFrame(); // 매개변수 없는 생성자 호출
        }
        return instance;
    }
    public void setOrder(OrderList order) {
        this.order = order;
        order.addObserver(this);
    }
    private void inputImage(){
        input.imageLabel("/image/Beverage.png", jLabel2);
        input.imageLabel("/image/Popcorn.png", jLabel3);
        input.imageButt("/image/ShoppingCart.png", ShoppingCartButton);
    }
    
     @Override
    public void updateObserver(String menu, String size, int cost, int countOrder) {
        this.countOrder = countOrder;
        display();
    }

    private void requestDeleteObserver() {
        this.menu = "";
        this.size = "";
        this.cost = 0;
        OrderList order = OrderList.getInstance();
        order.receiveOrderList(menu, size, cost);
    }
    
    @Override
    public void display() {
        setCountOrder.setText(Integer.toString(countOrder));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        previousFrameButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        ShoppingCartButton = new javax.swing.JButton();
        BeverageFrameButton = new javax.swing.JButton();
        PopcornFrameButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        setCountOrder = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(232, 232, 232));

        previousFrameButton.setBackground(new java.awt.Color(204, 204, 204));
        previousFrameButton.setText("←");
        previousFrameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                previousFrameButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("맑은 고딕", 0, 18)); // NOI18N
        jLabel1.setText("스위트샵");

        ShoppingCartButton.setBackground(new java.awt.Color(232, 232, 232));
        ShoppingCartButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShoppingCartButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ShoppingCartButton, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(previousFrameButton, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(previousFrameButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(ShoppingCartButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        BeverageFrameButton.setBackground(new java.awt.Color(204, 204, 204));
        BeverageFrameButton.setText("담기");
        BeverageFrameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BeverageFrameButtonActionPerformed(evt);
            }
        });

        PopcornFrameButton.setBackground(new java.awt.Color(204, 204, 204));
        PopcornFrameButton.setText("담기");
        PopcornFrameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PopcornFrameButtonActionPerformed(evt);
            }
        });

        setCountOrder.setFont(new java.awt.Font("맑은 고딕", 0, 14)); // NOI18N
        setCountOrder.setText("0");

        jLabel6.setFont(new java.awt.Font("맑은 고딕", 0, 14)); // NOI18N
        jLabel6.setText("주문갯수 : ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BeverageFrameButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(76, 76, 76))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(65, 65, 65)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PopcornFrameButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(79, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(setCountOrder)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(setCountOrder))
                .addGap(92, 92, 92)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BeverageFrameButton)
                    .addComponent(PopcornFrameButton))
                .addGap(150, 150, 150))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BeverageFrameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BeverageFrameButtonActionPerformed
        BeverageFrame beverage = BeverageFrame.getInstance();
        beverage.setVisible(true);
        dispose();
    }//GEN-LAST:event_BeverageFrameButtonActionPerformed

    private void PopcornFrameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PopcornFrameButtonActionPerformed
        PopcornFrame popcorn =PopcornFrame.getInstance();
        popcorn.setVisible(true);
        dispose();
    }//GEN-LAST:event_PopcornFrameButtonActionPerformed

    private void previousFrameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_previousFrameButtonActionPerformed
        requestDeleteObserver();
        SweetShopFacade facade = new SweetShopFacade();
        facade.offObserver();
        ShoppingCartFrame frame =  ShoppingCartFrame.getInstance();
        frame.getModel().setRowCount(0);
        UserMainFrame user = new UserMainFrame();
        user.setVisible(true);
        dispose();
    }//GEN-LAST:event_previousFrameButtonActionPerformed

    private void ShoppingCartButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShoppingCartButtonActionPerformed
       ShoppingCartFrame cart =ShoppingCartFrame.getInstance();
        cart.setVisible(true);
        dispose();
    }//GEN-LAST:event_ShoppingCartButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BeverageFrameButton;
    private javax.swing.JButton PopcornFrameButton;
    private javax.swing.JButton ShoppingCartButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton previousFrameButton;
    private javax.swing.JLabel setCountOrder;
    // End of variables declaration//GEN-END:variables

  
}
